### ISSUE TITLE
Duplicate test case titles

### ISSUE THREAD

**Issue by georgeben** [stevekinney/dropbear#2]
Hello @stevekinney The test case description in https://github.com/stevekinney/dropbear/blob/master/tests/parse.test.js#L21 is thesame as the test case description in https://github.com/stevekinney/dropbear/blob/master/tests/parse.test.js#L4.
Shouldn't the test case in https://github.com/stevekinney/dropbear/blob/master/tests/parse.test.js#L21 be 'should return a token with the type of Identifier for name tokens'?
Thanks

**Comment by Firanus** [comment]
Actually noticed a similar things myself and raised a PR for it. Hope that helps! :)

https://github.com/stevekinney/dropbear/pull/3
